/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current session CSRF token */
        get: operations["getAuthCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Restore the current authenticated member */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/flow-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read current authentication flow metadata
         * @description Phase 1 view of the normal flow identity and sequence fields. Recovery and pending-transition details remain outside this response. The recovery-cookie name contains the flow ID and issued sequence.
         */
        get: operations["getAuthFlowState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in an approved member */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a member registration for manual approval
         * @description Creates an unapproved user and never signs the user in. The password_confirm field is not accepted. While contact collection is disabled, omitted, null, or normalized-empty email/phone values are accepted and non-empty values receive field validation errors. No partial account is created on validation failure.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out the current browser session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read public catalog metadata */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List public archive apps
         * @description Returns publicly accessible apps ordered by created_at descending, then id descending. Subject facets describe the full accessible set and do not depend on search, grade, or page offset. Reject repeated and unknown query parameters.
         */
        get: operations["listPublicApps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an archive app available to the current member */
        get: operations["getApp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users and aggregate dashboard statistics
         * @description Pending users sort first, then creation time and member ID ascending. The page always carries aggregates for the full authorized member set.
         */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an approval target with its current account version */
        get: operations["getAdminUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/write-operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue an approval operation key */
        post: operations["createApprovalOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Explicitly set the approval value for one current target version */
        patch: operations["setAdminUserApproval"];
        trace?: never;
    };
    "/write-operations/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the minimal result for an approval key */
        get: operations["getApprovalOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/write-operations/{key}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an unresolved approval key without changing its target input */
        post: operations["cancelApprovalOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "user" | "admin";
        /** @enum {string} */
        SessionKind: "full" | "change_only";
        LoginInput: {
            login_id: string;
            password: string;
        };
        /** @description login_id and nickname are trimmed and normalized to NFC; password is normalized to NFC without trimming. Lengths count Unicode code points. Password length is 15-128 and common-password checks use the fixed server-side local blocklist. email and phone are optional synthetic Phase 1 inputs; password_confirm is never part of this request. */
        RegisterInput: {
            login_id: string;
            password: string;
            /** @description Trimmed NFC text; no newline, control, or bidi controls. */
            nickname: string;
            /** @description One address; local part case is preserved and the domain is normalized. No DNS or SMTP verification is performed. */
            email?: string | null;
            /** @description ASCII digits with an optional leading plus, spaces, and hyphens; the digit count must be 7-15. */
            phone?: string | null;
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            login_id: string;
            nickname: string;
            role: components["schemas"]["Role"];
            approved: boolean;
            /** @description Monotonic approval/credential version. Expected by approval writes; never exposed by public member DTOs. */
            account_version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            first_approved_at: string | null;
            /** Format: date-time */
            pending_expires_at: string | null;
        };
        AdminStats: {
            total_users: number;
            pending_users: number;
            total_apps: number;
            healthy_apps: number;
        };
        AdminUserPage: {
            items: components["schemas"]["AdminUser"][];
            pagination: components["schemas"]["Pagination"];
            stats: components["schemas"]["AdminStats"];
            /** Format: date-time */
            server_time: string;
        };
        CreateApprovalOperation: {
            /** @constant */
            kind: "user_approval";
            /** Format: uuid */
            target_id: string;
            expected_account_version: number;
            approved: boolean;
        };
        SetApprovalInput: {
            approved: boolean;
            expected_account_version: number;
        };
        ApprovalOperation: {
            /** Format: uuid */
            key: string;
            /** @constant */
            kind: "user_approval";
            /** Format: uuid */
            target_id: string;
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            expires_at: string;
            /** @enum {string} */
            state: "unresolved" | "succeeded" | "rejected";
            applied_account_version: number | null;
            applied_approved: boolean | null;
            /** Format: date-time */
            finalized_at: string | null;
            rejection_code: string | null;
        };
        RegisteredUser: {
            /** Format: uuid */
            id: string;
            login_id: string;
            nickname: string;
            /** @constant */
            approved: false;
            /** Format: date-time */
            pending_expires_at: string;
        };
        Self: {
            /** Format: uuid */
            id: string;
            login_id: string;
            nickname: string;
            role: components["schemas"]["Role"];
            approved: boolean;
            must_change_password: boolean;
            session_kind: components["schemas"]["SessionKind"];
            /** Format: date-time */
            expires_at: string;
            email?: string | null;
            phone?: string | null;
            /** Format: date-time */
            recent_auth_until?: string | null;
        } & (unknown & unknown);
        /** @description Phase 1 view of the identity and sequence fields from the approved authentication flow-state contract. Recovery and pending-transition details remain outside this view type. */
        AuthFlowContext: {
            /** Format: uuid */
            flow_id: string;
            revision: string;
            session_generation: string | null;
            last_identity_change_revision: string;
        };
        AuthResult: {
            user: components["schemas"]["Self"];
            csrf_token: string;
        };
        CsrfToken: {
            csrf_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        /** @enum {string} */
        Subject: "수학" | "과학" | "영어" | "역사" | "국어" | "사회" | "정보" | "기타";
        /** @enum {string} */
        Grade: "초1" | "초2" | "초3" | "초4" | "초5" | "초6" | "중1" | "중2" | "중3" | "고1" | "고2" | "고3";
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                fields?: {
                    [key: string]: string;
                };
                request_id: string | null;
                reasons?: string[];
                /** Format: date-time */
                retry_at?: string | null;
                /** Format: date-time */
                server_time?: string | null;
            };
        };
        Meta: {
            subjects: components["schemas"]["Subject"][];
            grades: components["schemas"]["Grade"][];
            themes: components["schemas"]["Theme"][];
            /** Format: date-time */
            server_time: string;
            capabilities: components["schemas"]["Capabilities"];
            support: components["schemas"]["Support"];
            initial_pending_days: number;
        };
        Theme: {
            id: string;
            name: string;
            pantone: string;
            from: string;
            to: string;
            /** @enum {string} */
            ink: "dark" | "light";
        };
        /** @enum {string} */
        Reason: "not_implemented" | "verification_pending" | "operational_restriction" | "collection_disabled";
        Capability: {
            enabled: boolean;
            reasons: components["schemas"]["Reason"][];
        };
        Capabilities: {
            apps_read: components["schemas"]["Capability"];
            auth_register: components["schemas"]["Capability"];
            auth_login: components["schemas"]["Capability"];
            auth_logout: components["schemas"]["Capability"];
            auth_password_change: components["schemas"]["Capability"];
            admin_users_read: components["schemas"]["Capability"];
            admin_approval: components["schemas"]["Capability"];
            admin_summary: components["schemas"]["Capability"];
            apps_create: components["schemas"]["Capability"];
            apps_update_own: components["schemas"]["Capability"];
            apps_delete_own: components["schemas"]["Capability"];
            admin_apps_read: components["schemas"]["Capability"];
            admin_apps_manage: components["schemas"]["Capability"];
            admin_reauth: components["schemas"]["Capability"];
            admin_password_reset: components["schemas"]["Capability"];
            admin_user_delete: components["schemas"]["Capability"];
            health_read: components["schemas"]["Capability"];
            health_check: components["schemas"]["Capability"];
            health_batch: components["schemas"]["Capability"];
            email_collection: components["schemas"]["Capability"];
            phone_collection: components["schemas"]["Capability"];
        };
        Support: {
            email: string | null;
            /** Format: uri */
            service_url: string | null;
            /** Format: uri */
            announcement_url: string | null;
        };
        Owner: {
            /** Format: uuid */
            id: string;
            nickname: string;
        };
        Pagination: {
            limit: number;
            offset: number;
            total: number;
            has_more: boolean;
        };
        /** @enum {string} */
        HealthState: "unchecked" | "healthy" | "http_error" | "timeout" | "network_error" | "blocked" | "redirect_error";
        HealthResult: {
            state: components["schemas"]["HealthState"];
            /** Format: date-time */
            checked_at: string | null;
            /** Format: date-time */
            fresh_until: string | null;
        };
        HealthView: {
            result: components["schemas"]["HealthResult"];
            latest_job: null | components["schemas"]["Job"];
            /** Format: date-time */
            next_check_at: string | null;
        };
        Job: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            finished_at: string | null;
            failure_code: string | null;
        };
        AppCard: {
            /** Format: uuid */
            id: string;
            owner: components["schemas"]["Owner"];
            name: string;
            subject: components["schemas"]["Subject"];
            grades: components["schemas"]["Grade"][];
            is_public: boolean;
            theme_id: string;
            version: number;
            url_version: number;
            health: components["schemas"]["HealthView"];
        };
        AppPage: {
            items: components["schemas"]["AppCard"][];
            pagination: components["schemas"]["Pagination"];
            /** Format: date-time */
            server_time: string;
            facets: {
                subjects_in_use: components["schemas"]["Subject"][];
            };
        };
        AppDetail: {
            /** Format: uuid */
            id: string;
            owner: components["schemas"]["Owner"];
            name: string;
            subject: components["schemas"]["Subject"];
            grades: components["schemas"]["Grade"][];
            is_public: boolean;
            theme_id: string;
            version: number;
            url_version: number;
            health: components["schemas"]["HealthView"];
            /** Format: uri */
            url: string;
            prompt: string;
            description: string;
            stack_db: string | null;
            stack_backend: string | null;
            stack_frontend: string | null;
            stack_hosting: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AppDetailResponse: {
            item: components["schemas"]["AppDetail"];
            /** Format: date-time */
            server_time: string;
        };
    };
    responses: {
        /** @description The app does not exist or is not accessible to the current member. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The request failed or the response could not be accepted. */
        ServiceError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Origin: string;
        CsrfToken: string;
        AuthFlowId: string;
        AuthRevision: string;
        SessionGeneration: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current CSRF token and expiry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfToken"];
                };
            };
            401: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current member; contact fields are excluded or null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Self"];
                };
            };
            401: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getAuthFlowState: {
        parameters: {
            query?: never;
            header: {
                "X-EduVibe-Flow-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authentication flow identity and sequence. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthFlowContext"];
                };
            };
            401: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Authenticated member and rotated CSRF token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            429: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInput"];
            };
        };
        responses: {
            /** @description Unapproved account and calculated pending expiry. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredUser"];
                };
            };
            400: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            413: components["responses"]["ServiceError"];
            422: components["responses"]["ServiceError"];
            429: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session was cleared or was already anonymous. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public catalog metadata and feature availability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            400: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    listPublicApps: {
        parameters: {
            query?: {
                /** @description Trim, normalize to NFC, then apply Unicode default case folding. Count the post-folded value in Unicode code points; reject values longer than 100 without truncation. Search name, author nickname, and description as separate substring fields. Treat percent and underscore literally; do not search login IDs or contact fields. */
                q?: string;
                /** @description Empty omits the filter; otherwise use one catalog value. */
                subject?: "" | components["schemas"]["Subject"];
                /** @description Empty omits the filter; otherwise use one catalog value. */
                grade?: "" | components["schemas"]["Grade"];
                /** @description Page size; defaults to 24 and cannot exceed 100. */
                limit?: number;
                /** @description Zero-based offset. A valid offset past the result count returns an empty page. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of public app cards. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppPage"];
                };
            };
            400: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public app detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetailResponse"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceError"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header: {
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An offset page and aggregate statistics for all users/apps. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getAdminUser: {
        parameters: {
            query?: never;
            header: {
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current target without contact fields. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    createApprovalOperation: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApprovalOperation"];
            };
        };
        responses: {
            /** @description An unresolved key result with no echoed business input. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOperation"];
                };
            };
            400: components["responses"]["ServiceError"];
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            422: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    setAdminUserApproval: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetApprovalInput"];
            };
        };
        responses: {
            /** @description The account state applied by this request. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            400: components["responses"]["ServiceError"];
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            410: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getApprovalOperation: {
        parameters: {
            query?: never;
            header: {
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unresolved is not success; the result does not expose input. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOperation"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            410: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    cancelApprovalOperation: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The result after cancellation; a prior success is not rolled back. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOperation"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            410: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
}
