/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Allocate a new mockable authentication flow identity */
        post: operations["createAuthFlow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/flows/{flow_id}/recovery-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue the first recovery credential for an unprepared flow */
        post: operations["issueRecoveryCookie"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/flows/{flow_id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm that the current recovery cookie was received */
        post: operations["confirmRecoveryCookie"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/flows/{flow_id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abandon only a flow that was never marked ready */
        post: operations["abandonAuthFlow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/recovery-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find only flows proved by a current recovery or session credential */
        get: operations["getAuthRecoveryContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/flows/{flow_id}/recovery-csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the existing recovery CSRF token without rotating it */
        get: operations["getRecoveryCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/flows/{flow_id}/recovery-cookie/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate recovery proof using the current full session */
        post: operations["rotateRecoveryCookie"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/flows/{flow_id}/restart-eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether an unproved flow can safely be replaced */
        get: operations["getRestartEligibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admit one authentication transition at an expected flow revision */
        post: operations["admitAuthTransition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/transitions/{transition_id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block late execution and settle or report an unavailable result */
        post: operations["settleAuthTransition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/transitions/{transition_id}/discard-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard only the session issued by a successful transition but not received */
        post: operations["discardAuthTransitionSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/flows/{flow_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explicitly reset only the flow proved by the supplied cookie */
        post: operations["resetAuthFlow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/anonymous-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue the first anonymous session after recovery preparation */
        post: operations["issueAnonymousSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the current session CSRF token without starting a new session
         * @description Reads only an existing valid session. Initial anonymous-session preparation uses POST /auth/anonymous-session.
         */
        get: operations["getAuthCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Restore the current authenticated member */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/flow-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read current authentication flow metadata
         * @description Reads the current flow, selected session, pending transition, and an optional requested transition result. Unavailable results are distinct from terminal transition states.
         */
        get: operations["getAuthFlowState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in an approved member */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a member registration for manual approval
         * @description Creates an unapproved user and never signs the user in. The password_confirm field is not accepted. While contact collection is disabled, omitted, null, or normalized-empty email/phone values are accepted and non-empty values receive field validation errors. No partial account is created on validation failure.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace the temporary password in a change-only session
         * @description Requires a valid change-only session. The password is normalized to NFC without trimming; confirmation stays in the browser and is not sent. The request is rejected when the temporary credential or session has expired, including at the exact expiry boundary.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out the current browser session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthenticate the current administrator without extending the absolute session expiry */
        post: operations["reauthenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read public catalog metadata */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List public archive apps
         * @description Returns publicly accessible apps ordered by created_at descending, then id descending. Subject facets describe the full accessible set and do not depend on search, grade, or page offset. Reject repeated and unknown query parameters.
         */
        get: operations["listPublicApps"];
        put?: never;
        /** Create an archive app with an issued operation key */
        post: operations["createApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an archive app available to the current member */
        get: operations["getApp"];
        put?: never;
        post?: never;
        /** Delete an owned archive app at its expected version */
        delete: operations["deleteApp"];
        options?: never;
        head?: never;
        /** Update an owned archive app at its expected version */
        patch: operations["updateApp"];
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users and aggregate dashboard statistics
         * @description Pending users sort first, then creation time and member ID ascending. The page always carries aggregates for the full authorized member set.
         */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an approval target with its current account version */
        get: operations["getAdminUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/write-operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a write operation key without changing app or account data */
        post: operations["createWriteOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Explicitly set the approval value for one current target version */
        patch: operations["setAdminUserApproval"];
        trace?: never;
    };
    "/admin/users/{id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a current ordinary member password to an administrator supplied temporary password */
        post: operations["resetAdminUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/write-operations/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the minimal result for a write operation key */
        get: operations["getWriteOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/write-operations/{key}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an unresolved approval or password reset key */
        post: operations["cancelWriteOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "user" | "admin";
        /** @enum {string} */
        SessionKind: "full" | "change_only";
        LoginInput: {
            login_id: string;
            password: string;
        };
        /** @description A new password of 15-128 Unicode code points. Normalize to NFC without trimming or truncation; compare the full normalized value against the versioned local common-password blocklist. Do not send it to an external service. The Phase 1 mock does not apply this check while list redistribution rights remain unresolved. The browser confirmation is never sent. */
        ChangePasswordInput: {
            password: string;
        };
        /** @description login_id and nickname are trimmed and normalized to NFC; password is normalized to NFC without trimming. Lengths count Unicode code points. Password length is 15-128. The production contract checks the full normalized value against the versioned local common-password blocklist; the Phase 1 mock does not apply the check while list redistribution rights remain unresolved. email and phone are optional synthetic Phase 1 inputs; password_confirm is never part of this request. */
        RegisterInput: {
            login_id: string;
            password: string;
            /** @description Trimmed NFC text; no newline, control, or bidi controls. */
            nickname: string;
            /** @description One address; local part case is preserved and the domain is normalized. No DNS or SMTP verification is performed. */
            email?: string | null;
            /** @description ASCII digits with an optional leading plus, spaces, and hyphens; the digit count must be 7-15. */
            phone?: string | null;
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            login_id: string;
            nickname: string;
            role: components["schemas"]["Role"];
            approved: boolean;
            /** @description Monotonic approval/credential version. Expected by approval writes; never exposed by public member DTOs. */
            account_version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            first_approved_at: string | null;
            /** Format: date-time */
            pending_expires_at: string | null;
        };
        AdminStats: {
            total_users: number;
            pending_users: number;
            total_apps: number;
            healthy_apps: number;
        };
        AdminUserPage: {
            items: components["schemas"]["AdminUser"][];
            pagination: components["schemas"]["Pagination"];
            stats: components["schemas"]["AdminStats"];
            /** Format: date-time */
            server_time: string;
        };
        CreateApprovalOperation: {
            /** @constant */
            kind: "user_approval";
            /** Format: uuid */
            target_id: string;
            expected_account_version: number;
            approved: boolean;
        };
        /** @description The new_password is included only in this key-issuance request and is never echoed or stored in the operation result. The implementation enforces a 16 KiB UTF-8 request limit and the shared 15–128 code point password policy. The versioned local common-password blocklist applies to the real API; Phase 1 mock does not apply that check. */
        CreatePasswordResetOperation: {
            /** @constant */
            kind: "user_password_reset";
            /** Format: uuid */
            target_id: string;
            expected_account_version: number;
            new_password: string;
        };
        CreateAppWriteOperation: {
            /** @constant */
            kind: "app_create";
            input: components["schemas"]["AppInput"];
        };
        CreateAppUpdateOperation: {
            /** @constant */
            kind: "app_update";
            /** Format: uuid */
            target_id: string;
            expected_version: number;
            input: components["schemas"]["AppPatch"];
        };
        CreateAppDeleteOperation: {
            /** @constant */
            kind: "app_delete";
            /** Format: uuid */
            target_id: string;
            expected_version: number;
        };
        CreateWriteOperation: components["schemas"]["CreateApprovalOperation"] | components["schemas"]["CreatePasswordResetOperation"] | components["schemas"]["CreateAppWriteOperation"] | components["schemas"]["CreateAppUpdateOperation"] | components["schemas"]["CreateAppDeleteOperation"];
        DeleteAppInput: {
            expected_version: number;
        };
        AppPatch: {
            name?: string;
            /** Format: uri */
            url?: string;
            prompt?: string;
            description?: string;
            subject?: components["schemas"]["Subject"];
            grades?: components["schemas"]["Grade"][];
            is_public?: boolean;
            theme_id?: string;
            stack_db?: string | null;
            stack_backend?: string | null;
            stack_frontend?: string | null;
            stack_hosting?: string | null;
        };
        UpdateAppInput: {
            expected_version: number;
            name?: string;
            /** Format: uri */
            url?: string;
            prompt?: string;
            description?: string;
            subject?: components["schemas"]["Subject"];
            grades?: components["schemas"]["Grade"][];
            is_public?: boolean;
            theme_id?: string;
            stack_db?: string | null;
            stack_backend?: string | null;
            stack_frontend?: string | null;
            stack_hosting?: string | null;
        };
        SetApprovalInput: {
            approved: boolean;
            expected_account_version: number;
        };
        /** @description The new_password is matched against the same key-issuance input and is never echoed or stored in the operation result. The implementation enforces a 16 KiB UTF-8 request limit and the shared 15–128 code point password policy. The versioned local common-password blocklist applies to the real API; Phase 1 mock does not apply that check. */
        SetPasswordResetInput: {
            new_password: string;
            expected_account_version: number;
        };
        ApprovalOperation: {
            /** Format: uuid */
            key: string;
            /** @constant */
            kind: "user_approval";
            /** Format: uuid */
            target_id: string;
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            expires_at: string;
            /** @enum {string} */
            state: "unresolved" | "succeeded" | "rejected";
            applied_account_version: number | null;
            applied_approved: boolean | null;
            /** Format: date-time */
            finalized_at: string | null;
            rejection_code: string | null;
            /** Format: date-time */
            server_time: string;
        };
        PasswordResetOperation: {
            /** Format: uuid */
            key: string;
            /** @constant */
            kind: "user_password_reset";
            /** Format: uuid */
            target_id: string;
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            expires_at: string;
            /** @enum {string} */
            state: "unresolved" | "succeeded" | "rejected";
            applied_account_version: number | null;
            /** Format: date-time */
            temporary_password_expires_at: string | null;
            /** Format: date-time */
            finalized_at: string | null;
            rejection_code: string | null;
            /** Format: date-time */
            server_time: string;
        };
        AppWriteOperation: {
            /** Format: uuid */
            key: string;
            /** @enum {string} */
            kind: "app_create" | "app_update" | "app_delete";
            /** Format: uuid */
            target_id: string | null;
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            expires_at: string;
            /** @enum {string} */
            state: "unresolved" | "confirming_deletion" | "succeeded" | "rejected";
            /** Format: date-time */
            db_applied_at: string | null;
            /** Format: date-time */
            finalized_at: string | null;
            /** @description Set only for a confirmed app create or update. */
            result_version: number | null;
            rejection_code: string | null;
            /** Format: date-time */
            server_time: string;
        };
        RegisteredUser: {
            /** Format: uuid */
            id: string;
            login_id: string;
            nickname: string;
            /** @constant */
            approved: false;
            /** Format: date-time */
            pending_expires_at: string;
        };
        Self: {
            /** Format: uuid */
            id: string;
            login_id: string;
            nickname: string;
            role: components["schemas"]["Role"];
            approved: boolean;
            must_change_password: boolean;
            session_kind: components["schemas"]["SessionKind"];
            /** Format: date-time */
            expires_at: string;
            email?: string | null;
            phone?: string | null;
            /** Format: date-time */
            recent_auth_until?: string | null;
        } & (unknown & unknown);
        AuthTransition: {
            transition_id: string;
            /** @enum {string} */
            availability: "available" | "unavailable";
            execution_blocked: boolean | null;
            /** @enum {string|null} */
            kind: "anonymous_session" | "login" | "logout" | "password_change" | "reauthenticate" | null;
            /** @enum {string|null} */
            state: "admitted" | "executing" | "succeeded" | "failed" | "cancelled" | "expired" | null;
            /** Format: date-time */
            permit_expires_at: string | null;
            result_session_generation: string | null;
            failure_code: string | null;
        };
        AuthFlowState: {
            /** Format: uuid */
            flow_id: string;
            revision: string;
            /** Format: date-time */
            server_time: string;
            /** Format: date-time */
            expires_at: string;
            recovery_ready: boolean;
            session_generation: string | null;
            session_cookie_present: boolean;
            last_identity_change_revision: string;
            pending_transition: components["schemas"]["AuthTransition"] | null;
            requested_transition: components["schemas"]["AuthTransition"] | null;
            next_transition_id: string | null;
        };
        CreateAuthFlowInput: {
            restart_from: string[];
        };
        AuthFlowCreated: {
            /** Format: uuid */
            flow_id: string;
            revision: string;
            /** Format: date-time */
            expires_at: string;
        };
        FlowRevision: {
            /** Format: uuid */
            flow_id: string;
            revision: string;
        };
        RecoveryCookieResult: {
            /** Format: uuid */
            flow_id: string;
            revision: string;
            recovery_csrf_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        RecoveryReady: {
            /** Format: uuid */
            flow_id: string;
            revision: string;
            /** Format: date-time */
            expires_at: string;
            /** @constant */
            ready: true;
        };
        RestartEligibility: {
            restart_eligible: boolean;
        };
        RecoveryContext: {
            items: components["schemas"]["RecoveryContextItem"][];
        };
        RecoveryContextItem: {
            /** Format: uuid */
            flow_id: string;
            revision: string;
            /** @enum {string} */
            proof_kind: "recovery" | "session";
        };
        RecoveryCsrf: {
            /** Format: uuid */
            flow_id: string;
            revision: string;
            recovery_csrf_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        ExpectedRevisionInput: {
            expected_revision: string;
        };
        RotateRecoveryCookieInput: {
            expected_revision: string;
            expected_session_generation: string;
        };
        AuthTransitionAdmissionInput: {
            /** Format: uuid */
            flow_id: string;
            transition_id: string;
            /** @enum {string} */
            kind: "anonymous_session" | "login" | "logout" | "password_change" | "reauthenticate";
            expected_revision: string;
            expected_session_generation: string | null;
        };
        AuthTransitionPermit: {
            /** Format: uuid */
            flow_id: string;
            transition_id: string;
            /** @enum {string} */
            kind: "anonymous_session" | "login" | "logout" | "password_change" | "reauthenticate";
            revision: string;
            /** Format: date-time */
            permit_expires_at: string;
        };
        SettleAuthTransitionInput: {
            /** Format: uuid */
            flow_id: string;
            expected_revision: string;
        };
        SettledAuthTransition: {
            /** Format: uuid */
            flow_id: string;
            revision: string;
            transition_id: string;
            result: components["schemas"]["AuthTransition"];
        };
        DiscardAuthSessionInput: {
            /** Format: uuid */
            flow_id: string;
            expected_revision: string;
            expected_session_generation: string;
        };
        ResetAuthFlowInput: {
            expected_revision: string;
            expected_session_generation?: string | null;
        };
        AnonymousSessionResult: {
            /** Format: uuid */
            flow_id: string;
            revision: string;
            session_generation: string;
            csrf_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        ReauthenticateInput: {
            password: string;
        };
        AuthResult: {
            user: components["schemas"]["Self"];
            csrf_token: string;
        };
        CsrfToken: {
            csrf_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        /** @enum {string} */
        Subject: "수학" | "과학" | "영어" | "역사" | "국어" | "사회" | "정보" | "기타";
        /** @enum {string} */
        Grade: "초1" | "초2" | "초3" | "초4" | "초5" | "초6" | "중1" | "중2" | "중3" | "고1" | "고2" | "고3";
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                fields?: {
                    [key: string]: string;
                };
                request_id: string | null;
                reasons?: string[];
                /** Format: date-time */
                retry_at?: string | null;
                /** Format: date-time */
                server_time?: string | null;
            };
        };
        Meta: {
            subjects: components["schemas"]["Subject"][];
            grades: components["schemas"]["Grade"][];
            themes: components["schemas"]["Theme"][];
            /** Format: date-time */
            server_time: string;
            capabilities: components["schemas"]["Capabilities"];
            support: components["schemas"]["Support"];
            initial_pending_days: number;
        };
        Theme: {
            id: string;
            name: string;
            pantone: string;
            from: string;
            to: string;
            /** @enum {string} */
            ink: "dark" | "light";
        };
        /** @enum {string} */
        Reason: "not_implemented" | "verification_pending" | "operational_restriction" | "collection_disabled";
        Capability: {
            enabled: boolean;
            reasons: components["schemas"]["Reason"][];
        };
        Capabilities: {
            apps_read: components["schemas"]["Capability"];
            auth_register: components["schemas"]["Capability"];
            auth_login: components["schemas"]["Capability"];
            auth_logout: components["schemas"]["Capability"];
            auth_password_change: components["schemas"]["Capability"];
            admin_users_read: components["schemas"]["Capability"];
            admin_approval: components["schemas"]["Capability"];
            admin_summary: components["schemas"]["Capability"];
            apps_create: components["schemas"]["Capability"];
            apps_update_own: components["schemas"]["Capability"];
            apps_delete_own: components["schemas"]["Capability"];
            admin_apps_read: components["schemas"]["Capability"];
            admin_apps_manage: components["schemas"]["Capability"];
            admin_reauth: components["schemas"]["Capability"];
            admin_password_reset: components["schemas"]["Capability"];
            admin_user_delete: components["schemas"]["Capability"];
            health_read: components["schemas"]["Capability"];
            health_check: components["schemas"]["Capability"];
            health_batch: components["schemas"]["Capability"];
            email_collection: components["schemas"]["Capability"];
            phone_collection: components["schemas"]["Capability"];
        };
        Support: {
            email: string | null;
            /** Format: uri */
            service_url: string | null;
            /** Format: uri */
            announcement_url: string | null;
        };
        Owner: {
            /** Format: uuid */
            id: string;
            nickname: string;
        };
        Pagination: {
            limit: number;
            offset: number;
            total: number;
            has_more: boolean;
        };
        /** @enum {string} */
        HealthState: "unchecked" | "healthy" | "http_error" | "timeout" | "network_error" | "blocked" | "redirect_error";
        HealthResult: {
            state: components["schemas"]["HealthState"];
            /** Format: date-time */
            checked_at: string | null;
            /** Format: date-time */
            fresh_until: string | null;
        };
        HealthView: {
            result: components["schemas"]["HealthResult"];
            latest_job: null | components["schemas"]["Job"];
            /** Format: date-time */
            next_check_at: string | null;
        };
        Job: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            finished_at: string | null;
            failure_code: string | null;
        };
        AppCard: {
            /** Format: uuid */
            id: string;
            owner: components["schemas"]["Owner"];
            name: string;
            subject: components["schemas"]["Subject"];
            grades: components["schemas"]["Grade"][];
            is_public: boolean;
            theme_id: string;
            version: number;
            url_version: number;
            health: components["schemas"]["HealthView"];
        };
        AppPage: {
            items: components["schemas"]["AppCard"][];
            pagination: components["schemas"]["Pagination"];
            /** Format: date-time */
            server_time: string;
            facets: {
                subjects_in_use: components["schemas"]["Subject"][];
            };
        };
        AppDetail: {
            /** Format: uuid */
            id: string;
            owner: components["schemas"]["Owner"];
            name: string;
            subject: components["schemas"]["Subject"];
            grades: components["schemas"]["Grade"][];
            is_public: boolean;
            theme_id: string;
            version: number;
            url_version: number;
            health: components["schemas"]["HealthView"];
            /** Format: uri */
            url: string;
            prompt: string;
            description: string;
            stack_db: string | null;
            stack_backend: string | null;
            stack_frontend: string | null;
            stack_hosting: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AppDetailResponse: {
            item: components["schemas"]["AppDetail"];
            /** Format: date-time */
            server_time: string;
        };
        AppInput: {
            name: string;
            /** Format: uri */
            url: string;
            prompt: string;
            description: string;
            subject: components["schemas"]["Subject"];
            grades: components["schemas"]["Grade"][];
            is_public: boolean;
            theme_id: string;
            stack_db: string | null;
            stack_backend: string | null;
            stack_frontend: string | null;
            stack_hosting: string | null;
        };
    };
    responses: {
        /** @description The app does not exist or is not accessible to the current member. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The request failed or the response could not be accepted. */
        ServiceError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        FlowPathId: string;
        TransitionPathId: string;
        Origin: string;
        CsrfToken: string;
        AuthFlowId: string;
        AuthRevision: string;
        SessionGeneration: string;
        TransitionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAuthFlow: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAuthFlowInput"];
            };
        };
        responses: {
            /** @description New flow identity; no credential is issued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthFlowCreated"];
                };
            };
            409: components["responses"]["ServiceError"];
            429: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    issueRecoveryCookie: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
            };
            path: {
                flow_id: components["parameters"]["FlowPathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A new non-persistent recovery cookie was issued. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCookieResult"];
                };
            };
            409: components["responses"]["ServiceError"];
            429: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    confirmRecoveryCookie: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                flow_id: components["parameters"]["FlowPathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedRevisionInput"];
            };
        };
        responses: {
            /** @description Recovery credential receipt confirmed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryReady"];
                };
            };
            401: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    abandonAuthFlow: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
            };
            path: {
                flow_id: components["parameters"]["FlowPathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The unprepared flow may be replaced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartEligibility"];
                };
            };
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getAuthRecoveryContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proved flow IDs only; no member or transition result data. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryContext"];
                };
            };
            401: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getRecoveryCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flow_id: components["parameters"]["FlowPathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Existing recovery CSRF token; no lifetime extension. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCsrf"];
                };
            };
            401: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    rotateRecoveryCookie: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                flow_id: components["parameters"]["FlowPathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateRecoveryCookieInput"];
            };
        };
        responses: {
            /** @description A new recovery credential; current session and expiry are preserved. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCookieResult"];
                };
            };
            401: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getRestartEligibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flow_id: components["parameters"]["FlowPathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eligibility only; no flow mutation or result lookup. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartEligibility"];
                };
            };
            404: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    admitAuthTransition: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthTransitionAdmissionInput"];
            };
        };
        responses: {
            /** @description One-use transition permit; credentials and request body are not stored. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTransitionPermit"];
                };
            };
            401: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            429: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    settleAuthTransition: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                transition_id: components["parameters"]["TransitionPathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettleAuthTransitionInput"];
            };
        };
        responses: {
            /** @description Safe terminal summary; prior success is never rolled back. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettledAuthTransition"];
                };
            };
            401: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    discardAuthTransitionSession: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                transition_id: components["parameters"]["TransitionPathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscardAuthSessionInput"];
            };
        };
        responses: {
            /** @description The exact missing session was discarded; other generations are unchanged. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowRevision"];
                };
            };
            401: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    resetAuthFlow: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                flow_id: components["parameters"]["FlowPathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetAuthFlowInput"];
            };
        };
        responses: {
            /** @description The proved flow was ended and can be restarted. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartEligibility"];
                };
            };
            401: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    issueAnonymousSession: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Transition-Id": components["parameters"]["TransitionId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedRevisionInput"];
            };
        };
        responses: {
            /** @description Anonymous session and its current CSRF token. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnonymousSessionResult"];
                };
            };
            401: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getAuthCsrf: {
        parameters: {
            query?: never;
            header: {
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current CSRF token and expiry. */
            200: {
                headers: {
                    "X-EduVibe-Flow-Id"?: string;
                    "X-EduVibe-Auth-Revision"?: string;
                    "X-EduVibe-Session-Generation"?: string;
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfToken"];
                };
            };
            401: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header: {
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current member; contact fields are excluded or null. */
            200: {
                headers: {
                    "X-EduVibe-Flow-Id"?: string;
                    "X-EduVibe-Auth-Revision"?: string;
                    "X-EduVibe-Session-Generation"?: string;
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Self"];
                };
            };
            401: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getAuthFlowState: {
        parameters: {
            query?: {
                transition_id?: string;
            };
            header: {
                "X-EduVibe-Flow-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authentication flow identity and sequence. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthFlowState"];
                };
            };
            401: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
                "X-EduVibe-Transition-Id": components["parameters"]["TransitionId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Authenticated member and rotated CSRF token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            429: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInput"];
            };
        };
        responses: {
            /** @description Unapproved account and calculated pending expiry. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredUser"];
                };
            };
            400: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            413: components["responses"]["ServiceError"];
            422: components["responses"]["ServiceError"];
            429: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
                "X-EduVibe-Transition-Id": components["parameters"]["TransitionId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInput"];
            };
        };
        responses: {
            /** @description The temporary credential is consumed and a full session is issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            422: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
                "X-EduVibe-Transition-Id": components["parameters"]["TransitionId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session was cleared or was already anonymous. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    reauthenticate: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
                "X-EduVibe-Transition-Id": components["parameters"]["TransitionId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReauthenticateInput"];
            };
        };
        responses: {
            /** @description Current administrator session and CSRF are rotated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public catalog metadata and feature availability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            400: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    listPublicApps: {
        parameters: {
            query?: {
                /** @description Trim, normalize to NFC, then apply Unicode default case folding. Count the post-folded value in Unicode code points; reject values longer than 100 without truncation. Search name, author nickname, and description as separate substring fields. Treat percent and underscore literally; do not search login IDs or contact fields. */
                q?: string;
                /** @description Empty omits the filter; otherwise use one catalog value. */
                subject?: "" | components["schemas"]["Subject"];
                /** @description Empty omits the filter; otherwise use one catalog value. */
                grade?: "" | components["schemas"]["Grade"];
                /** @description Page size; defaults to 24 and cannot exceed 100. */
                limit?: number;
                /** @description Zero-based offset. A valid offset past the result count returns an empty page. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of public app cards. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppPage"];
                };
            };
            400: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    createApp: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppInput"];
            };
        };
        responses: {
            /** @description The persisted app and its current owner. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetailResponse"];
                };
            };
            400: components["responses"]["ServiceError"];
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            410: components["responses"]["ServiceError"];
            422: components["responses"]["ServiceError"];
            429: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public app detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetailResponse"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceError"];
        };
    };
    deleteApp: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAppInput"];
            };
        };
        responses: {
            /** @description The app and its related health result and jobs were deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ServiceError"];
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            410: components["responses"]["ServiceError"];
            422: components["responses"]["ServiceError"];
            429: components["responses"]["ServiceError"];
            /** @description Includes DELETION_CONFIRMATION_PENDING when the app deletion is committed but its related deletion record is not yet confirmed. Check the existing operation key; do not submit a new key. */
            503: components["responses"]["ServiceError"];
        };
    };
    updateApp: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAppInput"];
            };
        };
        responses: {
            /** @description The persisted app at its new version. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetailResponse"];
                };
            };
            400: components["responses"]["ServiceError"];
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            410: components["responses"]["ServiceError"];
            422: components["responses"]["ServiceError"];
            429: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header: {
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An offset page and aggregate statistics for all users/apps. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getAdminUser: {
        parameters: {
            query?: never;
            header: {
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current target without contact fields. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    createWriteOperation: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWriteOperation"];
            };
        };
        responses: {
            /** @description An unresolved key result with no echoed business input. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOperation"] | components["schemas"]["PasswordResetOperation"] | components["schemas"]["AppWriteOperation"];
                };
            };
            400: components["responses"]["ServiceError"];
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            422: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    setAdminUserApproval: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetApprovalInput"];
            };
        };
        responses: {
            /** @description The account state applied by this request. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            400: components["responses"]["ServiceError"];
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            410: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    resetAdminUserPassword: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordResetInput"];
            };
        };
        responses: {
            /** @description The password was reset and the target's sessions were invalidated. */
            204: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ServiceError"];
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            410: components["responses"]["ServiceError"];
            413: components["responses"]["ServiceError"];
            422: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    getWriteOperation: {
        parameters: {
            query?: never;
            header: {
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unresolved is not success; the result does not expose input. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOperation"] | components["schemas"]["PasswordResetOperation"] | components["schemas"]["AppWriteOperation"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            410: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
    cancelWriteOperation: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-EduVibe-Flow-Id": components["parameters"]["AuthFlowId"];
                "X-EduVibe-Auth-Revision": components["parameters"]["AuthRevision"];
                "X-EduVibe-Session-Generation": components["parameters"]["SessionGeneration"];
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The result after cancellation; a prior success is not rolled back. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOperation"] | components["schemas"]["PasswordResetOperation"];
                };
            };
            401: components["responses"]["ServiceError"];
            403: components["responses"]["ServiceError"];
            404: components["responses"]["ServiceError"];
            409: components["responses"]["ServiceError"];
            410: components["responses"]["ServiceError"];
            503: components["responses"]["ServiceError"];
        };
    };
}
