import { describe, expect, it } from "vitest";
import uuidCases from "../../contracts/fixtures/uuid-cases.json";
import { readAuthRoute } from "../src/features/auth/auth-route";

describe("authentication route parameters", () => {
  it("accepts the edit return destination generated by the app", () => {
    expect(
      readAuthRoute(
        "?mode=login&return_to=%2Fapps%2F00000000-0000-4000-8000-000000000001%2Fedit",
      ),
    ).toEqual({
      mode: "login",
      returnTo: "/apps/00000000-0000-4000-8000-000000000001/edit",
      invalid: false,
    });
  });

  it.each([
    "/apps/00000000-0000-4000-8000-000000000001/edit?x=1",
    "/apps/00000000-0000-4000-8000-000000000001/edit?",
    "/apps/not-uuid/edit",
    "/apps/00000000-0000-4000-8000-000000000001/edit/extra",
    "//evil/apps/00000000-0000-4000-8000-000000000001/edit",
    "https://evil/apps/00000000-0000-4000-8000-000000000001/edit",
    "/apps/00000000-0000-4000-8000-000000000001\\edit",
    "/apps/00000000-0000-4000-8000-000000000001/edit#secret",
    "/apps/00000000-0000-4000-8000-000000000001/%65dit",
    "/apps/00000000-0000-4000-8000-000000000001/edit\n",
    "/apps/00000000-0000-4000-8000-000000000001/edit\u0085",
    "/apps/new",
  ])("rejects unsafe or unsupported edit return destination %j", (returnTo) => {
    expect(
      readAuthRoute(`?mode=login&return_to=${encodeURIComponent(returnTo)}`),
    ).toEqual({ mode: "login", returnTo: "/", invalid: true });
  });

  it("accepts the supported modes and safe internal destinations", () => {
    expect(readAuthRoute("")).toEqual({
      mode: "login",
      returnTo: "/",
      invalid: false,
    });
    expect(
      readAuthRoute(
        "?mode=login&return_to=%2Fapps%2F00000000-0000-4000-8000-000000000001",
      ),
    ).toMatchObject({
      mode: "login",
      returnTo: "/apps/00000000-0000-4000-8000-000000000001",
      invalid: false,
    });
    expect(readAuthRoute("?mode=signup").mode).toBe("signup");
    expect(
      readAuthRoute("?mode=password-change&return_to=%2Fadmin"),
    ).toMatchObject({
      mode: "password-change",
      returnTo: "/admin",
      invalid: false,
    });
    expect(
      readAuthRoute(
        "?return_to=%2F%3Fsubject%3D%25EC%2588%2598%25ED%2595%2599",
      ),
    ).toMatchObject({ invalid: false });
  });

  it("rejects external, duplicated, malformed, and repeated-decoding routes", () => {
    for (const search of [
      "?mode=unknown",
      "?mode=login&mode=reauth",
      "?mode=login&return_to=https%3A%2F%2Fexample.com",
      "?mode=login&return_to=%2F%2Fevil.example",
      "?mode=login&return_to=%252F%252Fevil.example",
      "?mode=login&return_to=%2Fauth%3Fmode%3Dlogin",
      "?mode=login&return_to=%2F%3Fq%3Done%26q%3Dtwice",
      "?mode=login&return_to=%2F%3Funknown%3Dvalue",
      "?mode=login&return_to=%2Fadmin%3F",
      "?mode=login&return_to=%2Fapps%2F00000000-0000-4000-8000-000000000001%3F",
      "?mode=login&return_to=%2F%C2%85admin",
      "?mode=%E0%A4%A",
    ])
      expect(readAuthRoute(search).invalid).toBe(true);
  });
});

describe("UUID boundaries in login return destinations", () => {
  it.each(uuidCases.valid)(
    "accepts %j without changing the destination",
    (id) => {
      const returnTo = `/apps/${id}`;
      expect(
        readAuthRoute(`?return_to=${encodeURIComponent(returnTo)}`),
      ).toEqual({ mode: "login", returnTo, invalid: false });
    },
  );

  it.each(uuidCases.invalid)(
    "rejects %j with the existing safe fallback",
    (id) => {
      expect(
        readAuthRoute(`?return_to=${encodeURIComponent(`/apps/${id}`)}`),
      ).toEqual({ mode: "login", returnTo: "/", invalid: true });
    },
  );
});
